### ISSUE TITLE
Suggestion: jQuery reload to avoid blank iframe

### ISSUE THREAD

**Issue by dav01it** [phpBB-Studio/Google-PDF-autoembed#1]
Sometimes the iframe fails to load and I get no pdf attachment->blank iframe

I read this post :[https://stackoverflow.com/questions/40414039/google-docs-viewer-returning-204-responses-no-longer-working-alternatives#comment68102437_40425780]( https://stackoverflow.com/questions/40414039/google-docs-viewer-returning-204-responses-no-longer-working-alternatives#comment68102437_40425780)

in particular "Cellydy" solution

I added it and I'm testing it.
modified: attachment_file_append.html with that script
and also pdf.css

**Comment by 3D-I** [comment]
Interesting.

Could you please make a PR so that we can test and evaluate it?

Regards.

**Comment by dav01it** [comment]
It does not work as expected since sometimes gview gives empty visible output but html loads anyway.
So I decided to add a "reload" button.
